# Generated by Django 5.2.5 on 2025-09-23 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilometreLidarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text="Identifiant unique de l'utilisateur ou du véhicule", max_length=150)),
                ('session_id', models.CharField(help_text='Identifiant unique de la session (profilomètre + lidar)', max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date et heure de la capture (session)')),
                ('json_data', models.JSONField(help_text='Données complètes : profilomètre + lidar (format x,y,z) + metadata')),
                ('has_lidar_data', models.BooleanField(db_index=True, default=False)),
                ('has_personality_data', models.BooleanField(db_index=True, default=False)),
                ('lidar_point_count', models.IntegerField(db_index=True, default=0)),
                ('lidar_capture_duration_sec', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donnée Profilomètre + LiDAR (x,y,z)',
                'verbose_name_plural': 'Données Profilomètre + LiDAR (x,y,z)',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='backapp_pro_user_id_0408f5_idx'), models.Index(fields=['has_lidar_data', 'lidar_point_count'], name='backapp_pro_has_lid_553acc_idx')],
            },
        ),
    ]
