# Generated by Django 5.2.5 on 2025-10-08 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_profilometrelidardata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasession',
            name='device',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='session',
        ),
        migrations.RemoveField(
            model_name='deviceconfiguration',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceconfiguration',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='iot',
            name='user',
        ),
        migrations.RemoveField(
            model_name='iot',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='user',
        ),
        migrations.RenameField(
            model_name='devicemodel',
            old_name='name',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='specifications',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('date_assigned', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='backapp.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('max_distance', models.FloatField(default=50.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendeurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_models', to='backapp.vendeurprofile'),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapp.devicemodel')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='backapp.vendeurprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DataBatch',
        ),
        migrations.DeleteModel(
            name='DataSession',
        ),
        migrations.DeleteModel(
            name='DeviceConfiguration',
        ),
        migrations.DeleteModel(
            name='IoT',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Vendeur',
        ),
    ]
